### ISSUE TITLE
Cannot export stories.

### ISSUE THREAD

**Issue by zeroshadow1234556** [towerofpower256/WritingExporter.SimpleExporter#6]
I keep getting the message that interactives aren't available when trying to export stories. What can I do?

**Comment by towerofpower256** [comment]
Hi zeroshadow12345,

What is the message that it's saying in the logs? Is it something along the lines of "Interactives are temporarily unavailable", and it starts a 15 second delay? Screenshots would be awesome.

If so, that's the pain of Writing.com and the reason why I started the project: the delays were too long and you lose patience. Unfortunately, the only ways I know of to get around it is to pay for a Writing.com account, or to start the exporter and let it run for a long time, typically overnight for larger stories.

**Comment by left1000** [comment]
make any progress on getting the paid account's to work?

**Comment by towerofpower256** [comment]
Sadly Writing.com have made more changes than I thought.
I'm currently working on re-doing how I read the pages, maybe moving away from Regex and using a purpose-built library such as the HTML Agility Pack.
