### ISSUE TITLE
"Dynamic Interactive" warning on every interactive story

### ISSUE THREAD

**Issue by infdre** [towerofpower256/WritingExporter.SimpleExporter#7]
I have been using this tool endlessly, and I thank you so much for your work!

In the past few weeks, an issue has come up. The most recent commit (https://github.com/towerofpower256/WritingExporter.SimpleExporter/commit/4d33fd3efef593eebcf27750c4a1ef7b43b69c2a) about dynamic interactives not being supported catches `WritingClientHtmlParseException`, and I believe that the devs at writing.com have changed the HTML structure, which results in this error being displayed on every interactive, despite the "dynamic interactives" option not being enabled (in fact, I have a free account).

When I print the response, everything looks normal (a signed in page with the contents of the chapter being displayed with no issues.)

I am not well-versed in C# but I am currently looking for a solution. Until then, I wanted to create an issue to get it out there. Again, thanks for this piece of software, it's really awesome!

Update: It appears that the parser cannot access the chapter title, as I am getting the following error:

```
> ERROR - An error occurred while trying to export the story.
WritingExporter.SimpleExporter.Exceptions.WritingClientHtmlParseException
Couldn't find the chapter title for chapter [redacted url]
```

I will continue to dig around!

**Comment by towerofpower256** [comment]
Gday infdre. Thanks, I'm really happy that you like it!

I'll have a look around and see what can be done.

If you're keen, WritingExporter.SimpleExporter works using a series of Regex searches in the HTML to find what it believes should be what it's looking for.

For example, the search for the chapter title happens in WritingClient.cs under the function GetInteractiveChapter on line 270. What I usually do to fine-tune the Regex is to use a Regex tester like https://regex101.com/, copy and paste the HTML for the Writing.com chapter into the body, and fiddle around with the Regex until it works.

The current Regex for the chapter title is:
`(?<=<big><big><b>).*?(?=<\/b><\/big><\/big>)`
which is looking for something wrapped in a <b> element and 2x <big> elements. I'd say this has changed in Writing.com and needs to be updated in the exporter.

**Comment by infdre** [comment]
From my testing, the following RegEx captures the chapter title:

```regex
(?<=<span style=\"font-size:1.5em;font-weight:bold;\">).+(?=<\/span> )
```

Although I haven't tried building the .exe!

**Comment by towerofpower256** [comment]
Thanks for that infdre, I've accepted the pull request.
